[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]

  topics = [
    "boat/engine/data"
  ]

  data_format = "json"

  name_override = "engine"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]

  token = "DZ8QC0X4uGyfRm6eqZTj0hQ3Jeo3QE9b8qaG50mUad-CRtNxYyZNuTQvFzCLLpgeLiH7guyus_3N23bvT8rAsg=="

  organization = "marine"

  bucket = "boat"